### ISSUE TITLE
Unable to install KE via Edge even with ClickOnce installed

### ISSUE THREAD

**Issue by henrik-me** [MicrosoftDocs/dataexplorer-docs#412] opened 2020-10-27 04:56 UTC
the aka.ms/ke and mirror links doesn't allow me to download kusto explorer on the new edge even with the ClickOnce for Google chrome installed.

Works fine when using Internet Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Kusto.Explorer installation and user interface](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by JayaChatterjee-MSFT** [comment] 2020-10-27 05:33
Thank you for your feedback! We will review and update as appropriate.

**Comment by HarithaMaddi-MSFT** [comment] 2020-10-27 06:27
@henrik-me - I have observed that it is giving a pop-up on the new edge, please try allowing pop-ups and let us know if it works.

**Comment by henrik-me** [comment] 2020-10-27 07:13
For me the redirect doesn't even happen on Edge (86.0.622.51). PoP-up blocker doesn't say anything about blocked (other aka.ms links works fine for redirects). Same issue with pop-up blocker completely disabled.

**Comment by HarithaMaddi-MSFT** [comment] 2020-10-27 07:37
@henrik-me - Thanks for confirming the details. As I am unable to reproduce the same, moving it to content author for further thoughts.

@orspod - Can you please take a look and suggest.

**Comment by orspod** [comment] 2020-10-27 12:10
@sloutsky - can you assist @henrik-me ?

**Comment by sloutsky** [comment] 2020-10-27 12:24
Please check if the following article helps:

https://smartofficeblog.com/2020/02/19/microsoft-edge-chromium-and-clickonce/

**Comment by orspod** [comment] 2020-10-28 08:12
@henrik-me was the article mentioned by @sloutsky helpful in solving your issue?

**Comment by orspod** [comment] 2020-11-02 09:31
@henrik-me - I assume your question was addressed. I will now close this issue.

**Closed by orspod** 2020-11-02 09:31 UTC
Labels: Pri2, assigned-to-author, data-explorer/svc, doc-enhancement, triaged

**Comment by henrik-me** [comment] 2020-11-02 16:42
No this doesn't help me, ClickOnce doesn't work for for me on Edge Chromium. 
My workaround was to open IE and install KE using IE 
(using the ClickOnce for Google Chrome extension only works if .net 3.5 is installed and I prefer to not have that on my system).
