### ISSUE TITLE
Documentation page for Kusto (and *only this specific page*) renders in high-contrast mode when dark mode is selected

### ISSUE THREAD

**Issue by elmarsto** [MicrosoftDocs/dataexplorer-docs#631] opened 2021-02-26 02:13 UTC
[Enter feedback here]
![image](https://user-images.githubusercontent.com/315987/109245366-32243c00-7795-11eb-9281-57e7157ed33a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62643597-337f-69f2-2ed9-bc9e6ddc1bf7
* Version Independent ID: 3f140887-e703-105c-1b27-e29e3b001324
* Content: [as operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/asoperator)
* Content Source: [data-explorer/kusto/query/asoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/asoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AshokPeddakotla-MSFT** [comment] 2021-02-26 05:02
@elmarsto Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment] 2021-02-28 18:57
Hi @AshokPeddakotla-MSFT - this looks like more of a docs ops question than a docs question. I am unable to reproduce the difference between this doc and any others in dark mode.

**Comment by elmarsto** [comment] 2021-03-01 03:06
yeah almost immediately after I left this the problem occurred on other pages. It was uncanny.  suspect some rollout somewhere

**Comment by AshokPeddakotla-MSFT** [comment] 2021-03-01 04:29
@YaelSchuster Thanks for looking into this issue. 
@elmarsto Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by AshokPeddakotla-MSFT** 2021-03-01 04:29 UTC
Labels: Pri1, assigned-to-author, data-explorer/svc, docs-experience, triaged
