### ISSUE TITLE
Monitor Cluster Health

### ISSUE THREAD

**Issue by TechieWorld** [MicrosoftDocs/dataexplorer-docs#73] opened 2020-05-12 06:47 UTC
Hi Team,

Can we create alert over .show diagnostics | IsHealthy command or shall we used the "KeepAlive" Metric?

Also, we noticed that "KeepAlive" is showing count as 0 sometimes. Metric is just an initial indicator for an issue but where I can find more details and investigate why cluster was not healthy during when we noticed "KeepAlive" was 0.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a338c71f-e871-3618-7125-1ca4f27b9ae4
* Version Independent ID: 1448ae00-e0a4-3a75-58e8-790f60a3aba3
* Content: [Check the health of an Azure Data Explorer cluster](https://docs.microsoft.com/en-us/azure/data-explorer/check-cluster-health)
* Content Source: [data-explorer/check-cluster-health.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/check-cluster-health.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ChiragMishra-MSFT** [comment] 2020-05-12 10:31
@orspod Can you please look at this?

**Comment by Gabilehner** [comment] 2020-05-18 14:58
KeepAlive is a general top level metric to check your cluster health. when the value is 0 it means the cluster was not responding which is a non healthy state.
When this metric goes to 0, you should start a more in depth analysis to find the root cause of the issue using other troubleshooting flows and other metrics.
In order to get more insights you can also use the .show commands and queries operation - https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/commands-and-queries
We're also working on a new capability that will expose this information in an easier way.

**Comment by orspod** [comment] 2020-05-19 09:38
@Gabilehner  thanks for the detailed explanation. @TechieWorld - please let us know if this resolves your issue.

**Comment by TechieWorld** [comment] 2020-05-19 13:49
@Gabilehner  - can you please let me know where I can find more details on why KeepMetric is showing 0, I didn't find anything with .show commands and queries?

**Comment by Gabilehner** [comment] 2020-05-25 04:35
@TechieWorld - as I mentioned KeepAlive metric is a general purpose health metric. When the value is 0 it tells you that something is not working well but It cannot provide you the root cause. This requires an analysis that can be done using other metrics (for example CPU, in case the issue stems from overload on the cluster), Another example, is to run the .show commands-and-queries to analyze heavy operations done on the cluster. 
There are numerous investigations that can be done on your cluster to analyze its health and we keep releasing more features to improve the ease of analysis and add more options to investigate.

Thanks,
Gabi

**Comment by orspod** [comment] 2020-05-31 06:30
@TechieWorld - I believe your question has been addressed. I am moving to close this issue.

**Closed by orspod** 2020-05-31 06:30 UTC
Labels: Pri2, assigned-to-author, data-explorer/svc, product-question, triaged
