### ISSUE TITLE
Multiple Join Keys example

### ISSUE THREAD

**Issue by mathaholic** [MicrosoftDocs/dataexplorer-docs#1498] opened 2022-11-11 23:16 UTC
please add an example of 

let b = table
           |some logic
           |distinct keyB, keyD, col1, col2;
a
| join kind=inner (b) on $left.keyA == $right.keyB, $left.keyC == $right.keyD

I've tried all permutations listed here:
https://stackoverflow.com/questions/58867033/kusto-kql-join-on-multiple-columns
and none of them worked

**Comment by SaibabaBalapur-MSFT** [comment] 2022-11-12 04:02
@mathaholic 
We are going to close this thread as resolved as duplicate case.
Duplicate of #1498

**Closed by SaibabaBalapur-MSFT** 2022-11-12 04:02 UTC
Labels: cxp, triaged, doc-bug, Pri3
