### ISSUE TITLE
Suggest alternatives for dynamic table creation if available

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/dataexplorer-docs#4] opened 2020-04-15 16:09 UTC
Documentation states following:
&gt; ScalarValue: A constant scalar value to insert into the table.
which is easy to understand. Is there any alternatives if I e.g. need to create datetime with ago()-function or refer data created with let statements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97de494f-8a36-e9ee-45f8-95c0ef540ae9
* Version Independent ID: 8af2d2f5-1512-1827-3c39-c27683155c18
* Content: [datatable operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatableoperator)
* Content Source: [data-explorer/kusto/query/datatableoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/datatableoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment] 2020-04-16 10:58
@jikuja - thank you for your contribution
@Mike-Ubezzi-MSFT - note issue in new repo
@yonileibowitz or @sloutsky please advise

**Comment by yonileibowitz** [comment] 2020-04-16 14:40
if i understand the question correctly, you could achieve that using the `print` operator
for example: `print dt1 = ago(7d), dt2 = now()+5m`.

as mentioned in the docs, the `datatable` operator requires scalar constant values (which `ago(7d)`, for example, is not)

**Comment by jikuja** [comment] 2020-04-16 16:52
Nice workaround but is there easy way to do multiline table?

**Comment by yonileibowitz** [comment] 2020-04-16 16:54
@jikuja, it may help if you provide your use case, and a sample for what you're trying to achieve.
reasoning: there are several ways, and we prefer providing you with one which is relevant to your use case (and not shoot in the dark)

**Comment by jikuja** [comment] 2020-04-16 17:10
My original plan was to do following:

```
let defaultValue = ago(2d);
let myData =
datatable (name:string, ts:datetime) [
        // --user sync--
        "foo", defaultValue,
        "bar", ago(1d),
        "baz", defaultValue
]
```
and this table is reused by joining with other tables. Looks like this idea has multiple issues I found out after writing first version of the code.

Changing data type partially fixes the problem:
```
//let defaultValue = ago(2d); 
let myData =
datatable (name:string, ts:timespan) [
        // --user sync--
        "foo", 2d,
        "bar", 1d,
        "baz", 2d
]
```

but this still has no easy way to define default value.

Because schema of myData is simply I probably should use dynamic object are rewrite joins I use for filtering with where clauses.

**Comment by yonileibowitz** [comment] 2020-04-16 17:14
thanks @jikuja.
how about this as an option?
```
let defaultValue = 2d;
let myData =
    datatable (name:string, ts:timespan) 
    [
        "foo", timespan(null),
        "bar", 1d,
        "baz", timespan(null)
    ]
    | project name, dt = now() - coalesce(ts, defaultValue)
;
myData
```

**Comment by jikuja** [comment] 2020-04-16 18:40
Thanks. That did the trick. Now I just need to choose the best approach.

**Comment by orspod** [comment] 2020-04-16 20:52
@yonileibowitz thanks for your assistance.
@jikuja, now that the issue is resolved, i am moving to close the issue.

**Closed by orspod** 2020-04-16 20:52 UTC
Labels: Pri1, data-explorer/svc
