### ISSUE TITLE
error feedback

### ISSUE THREAD

**Issue by sivanyuegmail** [MicrosoftDocs/dataexplorer-docs#189] opened 2020-06-30 06:04 UTC
[Enter feedback here]

curl -d '{"db":"Samples","csl":"print Test=\"Hello, World!\"","properties":"{\"Options\":{\"queryconsistency\":\"strongconsistency\"}}"}"'

最后一个}后满多了一个"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d046c47f-5e33-bff9-51fd-b8fa4905a260
* Version Independent ID: 49509522-8d22-75e4-8dc7-ec78ff83a045
* Content: [Query/management HTTP request - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/request)
* Content Source: [data-explorer/kusto/api/rest/request.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/request.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KrishnaG-MSFT** [comment] 2020-06-30 13:10
@sivanyuegmail Thanks for reaching out! Is this issue a duplicate of [#190](https://github.com/MicrosoftDocs/dataexplorer-docs/issues/190)? If Yes, please let me know so that I can close this issue. If No, please elaborate your feedback with more context.

**Comment by KrishnaG-MSFT** [comment] 2020-07-03 13:47
@sivanyuegmail Closing this issue as there was no further response.

**Closed by KrishnaG-MSFT** 2020-07-03 13:47 UTC
Labels: Pri2, cxp, data-explorer/svc, product-question, triaged
