### ISSUE TITLE
Query could not be parsed at 'extractjson' on line 

### ISSUE THREAD

**Issue by pbalajiips** [MicrosoftDocs/dataexplorer-docs#264] opened 2020-08-06 14:27 UTC
[Enter feedback here]
 Hi There, flunetbit running on our k8s cluster pushes json format logs to azure log analytics, and when i try to extract a specific field from the josn log using extractjson function i am getting below error.  anyone has idea on this...?

Query could not be parsed at 'extractjson' on line [5,2]

Token: extractjson
Line: 5
Position: 2
If issue persists, please open a support ticket. Request id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a9498f-3bba-5479-e7d7-32cc4d96c15a
* Version Independent ID: 198ef7fc-f118-3f0d-0c9b-366d3e008be0
* Content: [extractjson() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractjsonfunction)
* Content Source: [data-explorer/kusto/query/extractjsonfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/extractjsonfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment] 2020-08-06 16:44
@pbalajiips Thanks for reaching out. Since the issue is not a feedback on the doc in reference, I would recommend you to create a thread on the forums - [Microsoft Q&A ](https://docs.microsoft.com/en-us/answers/products/) or [stackoverflow](https://stackoverflow.com/). 

Once you post your issue on forums, it will have visibility across the community which has a better suited audience for such types of issues. We have our engineers and other community members who will be happy to assist. 

Please create a Forum thread and post it's link here and tag me so that we can track that thread.

If you have a document which you are following and if you think it needs an update, please let us know about that here.
I will now proceed to close this issue. Feel free to comment if you have any other queries.

Thank you.

**Closed by KranthiPakala-MSFT** 2020-08-06 16:44 UTC
Labels: Pri2, cxp, data-explorer/svc, forum, product-question, triaged
