### ISSUE TITLE
 Please select a database to execute queries.

### ISSUE THREAD

**Issue by evilches** [MicrosoftDocs/dataexplorer-docs#70] opened 2020-05-11 06:23 UTC
Running the example as is throws: "Please select a database to execute queries.". We should probably add something like "To run this query, click here and select the database 'Samples'. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef293ef5-6b7e-2fc4-fb62-838dd7d5e325
* Version Independent ID: bc13e5ac-5044-cca6-c314-7dc4d9da6cc9
* Content: [Overview - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/)
* Content Source: [data-explorer/kusto/query/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/index.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment] 2020-05-11 09:31
@evilches thanks for your feedback. I will investigate further.
@yonileibowitz any idea why it throws the error: "Please select a database to execute queries." Mine depicts properly. @YaelSchuster received the same error as @evilches the first time it was accessed but the second time it was scoped properly....

**Comment by yonileibowitz** [comment] 2020-05-11 15:03
@evilches, @YaelSchuster, @orspod - as the error message suggests - before running a query (any query), you need to select a database in the connections panel. a Kusto query must run in the context of a database, and can't run in a context of a cluster.

**Comment by yonileibowitz** [comment] 2020-05-17 04:24
this seems to be fixed now - @evilches could you please confirm, and resolve the issue if confirmed?

**Comment by orspod** [comment] 2020-05-19 09:34
@yonileibowitz and @lidermanrony thanks so much for the quick fix. @evilches please confirm that the issue has been resolved.

**Comment by evilches** [comment] 2020-05-19 19:03
It works perfectly now! :D. Thank you!

**Comment by orspod** [comment] 2020-05-20 13:42
@evilches - thanks again for your feedback. I will now close the issue.

**Closed by orspod** 2020-05-20 13:42 UTC
Labels: Pri1, assigned-to-author, data-explorer/svc, product-issue, triaged
