### ISSUE TITLE
How to enable Engive V3 when creating with ARM template?

### ISSUE THREAD

**Issue by kosinsky** [MicrosoftDocs/dataexplorer-docs#482] opened 2020-12-02 16:31 UTC
Doc shows only how to use portal to enabled V3 during cluster creation. Is it a way to do that using ARM template?

I tried to create V2 and V3 from portal and see differences in the exported template, unfortunately it's none.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad6d867d-04e9-eb00-6186-27c15896f26e
* Version Independent ID: 318da0c0-c574-981d-c2c2-6790e25ba492
* Content: [Azure Data Explorer Kusto EngineV3 (preview)](https://docs.microsoft.com/en-us/azure/data-explorer/engine-v3)
* Content Source: [data-explorer/engine-v3.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/engine-v3.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment] 2020-12-03 03:41
@kosinsky Thanks for your feedback. I have created a Work Item to update this document. 

Duplicate of #453

**Closed** 2020-12-03 03:41 UTC
Labels: cxp, data-explorer/svc, duplicate, triaged
