### ISSUE TITLE
The example should include something that actually works in Kusto, i.e.

### ISSUE THREAD

**Issue by rymusg** [MicrosoftDocs/dataexplorer-docs#1293] opened 2022-07-12 03:38 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d431578-4425-3bda-f5a5-1e048117893e
* Version Independent ID: 26c98c8f-350d-f8cf-f1fc-fb764b6049da
* Content: [iff() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/ifffunction)
* Content Source: [data-explorer/kusto/query/ifffunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/ifffunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment] 2022-07-12 06:02
Duplicate of #1294

**Closed by CHEEKATLAPRADEEP-MSFT** 2022-07-12 06:02 UTC
Labels: duplicate, data-explorer/svc, Pri1, cxp, triaged
