### ISSUE TITLE
How to specify "Retry" option for the async operation

### ISSUE THREAD

**Issue by githubavi** [MicrosoftDocs/dataexplorer-docs#242] opened 2020-07-29 10:00 UTC
Hi Team, is there any way we can apply "retry" for the async operation? As tested I have found operation details like below,
e.g.

"OperationId": 82f5c388-b01a-4d16-ac17-4e8930ff54ec,
"Operation": TableSetOrReplace,
"NodeId": ,
"StartedOn": 2020-07-29T09:56:58.4927571Z,
"LastUpdatedOn": 2020-07-29T09:56:58.8051836Z,
"Duration": 00:00:00.3124265,
"State": Completed,
"Status": ,
"RootActivityId": 3305839b-209a-4a5c-9162-0926b7f954be,
**"ShouldRetry": false**,
"Database": mytestdb,
"Principal": xxx
"User": xxx,
 
My question is, is there any way I can make "ShouldRetry" flag to true while specifying "async" operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dde8b71-b1d9-ddef-1879-7358813b16ab
* Version Independent ID: db750929-3467-bbe3-b753-8953070900dc
* Content: [Kusto query ingestion (set, append, replace) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-query)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-from-query.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-ingestion/ingest-from-query.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment] 2020-07-29 17:41
Hi @githubavi Thanks for reaching out. Since the issue is not a feedback on the doc in reference, I would recommend you to create a thread on the forums - [Microsoft Q&A ](https://docs.microsoft.com/en-us/answers/products/) or [stackoverflow](https://stackoverflow.com/). 

Once you post your issue on forums, it will have visibility across the community which has a better suited audience for such types of issues. We have our engineers and other community members who will be happy to assist. 

Please create a Forum thread and post it's link here and tag me so that we can track that thread.

I will now proceed to close this issue. Feel free to comment if you have any other queries.

**Closed by KranthiPakala-MSFT** 2020-07-29 17:41 UTC
Labels: Pri2, cxp, data-explorer/svc, forum, product-question, triaged
