### ISSUE TITLE
Sample code failure

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/dataexplorer-docs#754] opened 2021-07-28 03:21 UTC
When I run the sample code 

```
range x from -2 to 2 step 0.1
| extend sin = sin(x), cos = cos(x)
| extend x_sign = iif(x > 0, "x_pos", "x_neg")
| extend sum_sign = iif(sin + cos > 0, "sum_pos", "sum_neg")
| render linechart with  (ycolumns = sin, cos, series = x_sign, sum_sign)
```

I get 

> Failed to create visualization
> We currently don't support 'linechart' visualization type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment] 2021-07-28 05:13
@ElectricLlama  Thanks for the question! We are investigating and will update you shortly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment] 2021-07-28 06:01
@ElectricLlama As per my repro, I am able to view the  'linechart' visualization type without any issue.

![image](https://user-images.githubusercontent.com/79183421/127271332-7bac0207-8467-49a5-b274-e3f20b8be660.png)

Could you please share more details on the above error message (Failed to create visualization
We currently don't support 'linechart' visualization type.) which you are experiencing?

**Comment by ElectricLlama** [comment] 2021-07-29 23:07
Maybe it's because this is running in Application Insights. Shouldn't Kusto work the same everywhere?

![image](https://user-images.githubusercontent.com/3804276/127576492-f981a1f7-0382-4317-960b-ed484c2ca6b7.png)

**Comment by ElectricLlama** [comment] 2021-07-29 23:13
OK I see this doco is specifically for Azure Data Explorer. It seems like Kusto has different sets of functionality in Data Explorer vs Application Insights. /Log Analytics.

**Comment by KranthiPakala-MSFT** [comment] 2021-07-30 17:49
Hi @ElectricLlama, Yes this document is specific to Azure Data Explorer. And yes, both are two distinct products and varies by functionality. 

As the issue is not relevant to the document content in reference, we request you to please reach out in [Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/products/) where we have our engineers and other MVP's who will be happy to assist. 

If you have a doc-feedback or a doc enhancement request for a particular document, please feel free to share it here. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you

**Closed by KranthiPakala-MSFT** 2021-07-30 17:49 UTC
Labels: Pri1, cxp, data-explorer/svc, forum, product-question, triaged
